### ISSUE TITLE
gresource.h dependency problem

### ISSUE THREAD

**Issue by glococo** [Jeija/gtkterm#1]
Hi !

I trying to compile in Ubuntu 17.04 and fail on this:

term_config.c:48:23: fatal error: gresource.h: No such file or directory
 #include "gresource.h"

./confgure ran fine 

(packages installed libgio3.0-cil-dev, libvte-2.91-dev, libgtk-3-dev and intltool)
Thanks!

**Comment by Jeija** [comment]
I haven't tried to compile this on Ubuntu 17.04, but I was able to reproduce the issue on my Archlinux machine. https://github.com/Jeija/gtkterm/commit/11291f1b02cdf268ea5fa6530808d01d601ab2a7 should have hopefully fixed the issue (I forgot something and fixed that in https://github.com/Jeija/gtkterm/commit/7a9205eb20474c65306b0e5c5777132ade939bc5).

By the way, gtkterm is kind of a mess (source code is in a mix of English and French, build system is outdated, uses mostly outdated GTK+2 function calls etc.) and even though I started some work on improving it in this repo, I eventually gave up and wrote my own GTK serial port application: https://github.com/Jeija/espterm
Feature-wise it is not comparable with gtkterm (it is more intended for ESP8266 development), but if you're looking for a simple GTK+ 3 serial port application that you can easily modify and build on, it should fit your needs.

**Comment by glococo** [comment]
Hi Jeija, 

Thanks for the feedback and the commit. Now is compiling fine.
However the "View as Hex" is still failing and miss align hex columns.

![screenshot from 2017-05-27 15-29-25](https://cloud.githubusercontent.com/assets/1307647/26522178/6f8a862a-42f2-11e7-8985-e1b3cdfe07a5.png)

I use gtkTerm to debug avr mcu, use a lot the option "view as Hex" and Logging to file :)

**Comment by Jeija** [comment]
Yes, I don't use the "View as Hex" feature very much, so it might be broken. I'm not really interested in fixing it, sorry. If you feel like patching the bug, Pull Requests are welcome.

**Comment by glococo** [comment]
Hi, thanks for help and support,
but right now I have no idea of gtk, maybe in the future I could solve this bug :)
